# Generated by Django 6.0.2 on 2026-03-13 15:54

import administracion.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vida_util_cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('vida_util_unidad', models.CharField(choices=[('Minutos', 'Minutos'), ('Horas', 'Horas'), ('Dias', 'Dias'), ('Semanas', 'Semanas'), ('Meses', 'Meses'), ('Anios', 'Anios')], default='Horas', max_length=20)),
                ('potencia_watts', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('factor_uso_porcentaje', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bien',
                'verbose_name_plural': 'Bienes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_de_medida', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Onzas', 'Onzas'), ('Libras', 'Libras'), ('Metros', 'Metros'), ('Centimetros', 'Centimetros')], default='Unidades', max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('costo', models.FloatField(blank=True, default=0, null=True)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/recetas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), administracion.models.validate_image_size])),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('porciones', models.DecimalField(decimal_places=2, default=1, max_digits=15)),
                ('rentabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('mostrar', models.BooleanField(default=True, help_text='Permite mostrar la receta o producto')),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('iva', models.DecimalField(decimal_places=2, default=21, help_text='Selecciona la alícuota que corresponde a esta receta', max_digits=5)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.categoriareceta')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='ProductoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('medida_uso', models.CharField(choices=[('Unidades', 'Unidades'), ('Kilos', 'Kilos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Mt2s', 'Mt2s'), ('Onzas', 'Onzas'), ('Libras', 'Libras'), ('Metros', 'Metros'), ('Centimetros', 'Centimetros')], default='Unidades', max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'producto incluido',
                'verbose_name_plural': 'Productos incluidos',
            },
        ),
        migrations.CreateModel(
            name='PasosReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('detalle', models.TextField()),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'pasos',
                'verbose_name_plural': 'Pasos',
            },
        ),
        migrations.CreateModel(
            name='GastosAdicionalesReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'gasto',
                'verbose_name_plural': 'Gastos adicionales',
            },
        ),
        migrations.CreateModel(
            name='BienReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_uso_cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('tiempo_uso_unidad', models.CharField(choices=[('Minutos', 'Minutos'), ('Horas', 'Horas'), ('Dias', 'Dias'), ('Semanas', 'Semanas'), ('Meses', 'Meses'), ('Anios', 'Anios')], default='Minutos', max_length=20)),
                ('incluir_depreciacion', models.BooleanField(default=True)),
                ('incluir_electricidad', models.BooleanField(default=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.bien')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.receta')),
            ],
            options={
                'verbose_name': 'bien incluido',
                'verbose_name_plural': 'Bienes incluidos',
            },
        ),
    ]
