# Generated by Django 6.0.2 on 2026-03-13 15:54

import configuracion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_emprendimiento', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('redes_sociales', models.CharField(blank=True, max_length=200, null=True)),
                ('moneda', models.CharField(default='$', max_length=200)),
                ('precio_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), configuracion.models.validate_image_size])),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('redondeo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
