# Generated by Django 6.0.3 on 2026-03-15 15:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracion_segunda_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='tipo_de_cambio',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='Cuántas unidades de moneda principal equivalen a 1 unidad de segunda moneda. Ej: si 1 USD = 1000 $, ingresá 1000.', max_digits=20),
        ),
    ]
