# Generated by Django 6.0.3 on 2026-05-13 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_configuracion_redondeo_segunda_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='tipo_de_cambio',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='Cuántos USD (o segunda moneda) equivalen a 1 unidad de moneda principal. Ej: si 1 $ = 0,00069 USD, ingresá 0.00069.', max_digits=20),
        ),
    ]
